// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4._1Employee.Models;

namespace _4._1Employee.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200918201116_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_4._1Employee.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnName("dateofbirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("enddate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<DateTime>("HireDate")
                        .HasColumnName("hiredate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("lastname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("LocationID")
                        .HasColumnName("location_id")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("LocationID")
                        .HasName("FK_Employee_Location");

                    b.ToTable("employee");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            DateOfBirth = new DateTime(1959, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Olivia",
                            HireDate = new DateTime(2007, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jimenez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -2,
                            DateOfBirth = new DateTime(1963, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Benjamin",
                            HireDate = new DateTime(2004, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -3,
                            DateOfBirth = new DateTime(1973, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Melissa",
                            HireDate = new DateTime(2004, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patel",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -4,
                            DateOfBirth = new DateTime(1957, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christina",
                            HireDate = new DateTime(2014, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mendoza",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -5,
                            DateOfBirth = new DateTime(1968, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amanda",
                            HireDate = new DateTime(2001, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Robinson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -6,
                            DateOfBirth = new DateTime(1976, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Walter",
                            HireDate = new DateTime(2012, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wright",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -7,
                            DateOfBirth = new DateTime(1960, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Victoria",
                            HireDate = new DateTime(2007, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Williams",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -8,
                            DateOfBirth = new DateTime(1968, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jonathan",
                            HireDate = new DateTime(2010, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reed",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -9,
                            DateOfBirth = new DateTime(1953, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carol",
                            HireDate = new DateTime(2001, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lee",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -10,
                            DateOfBirth = new DateTime(1968, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Debra",
                            HireDate = new DateTime(2007, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Edwards",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -11,
                            DateOfBirth = new DateTime(1967, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joan",
                            HireDate = new DateTime(2000, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hernandez",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -12,
                            DateOfBirth = new DateTime(1967, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gregory",
                            HireDate = new DateTime(2012, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ortiz",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -13,
                            DateOfBirth = new DateTime(1950, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            HireDate = new DateTime(2002, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ruiz",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -14,
                            DateOfBirth = new DateTime(1965, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rose",
                            HireDate = new DateTime(2011, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Walker",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -15,
                            DateOfBirth = new DateTime(1951, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diana",
                            HireDate = new DateTime(2003, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roberts",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -16,
                            DateOfBirth = new DateTime(1979, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marilyn",
                            HireDate = new DateTime(2012, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mendoza",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -17,
                            DateOfBirth = new DateTime(1964, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Roy",
                            HireDate = new DateTime(2009, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Flores",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -18,
                            DateOfBirth = new DateTime(1965, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Karen",
                            HireDate = new DateTime(2013, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Howard",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -19,
                            DateOfBirth = new DateTime(1953, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ethan",
                            HireDate = new DateTime(2011, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mendoza",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -20,
                            DateOfBirth = new DateTime(1967, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jonathan",
                            HireDate = new DateTime(2006, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "James",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -21,
                            DateOfBirth = new DateTime(1969, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Juan",
                            HireDate = new DateTime(2003, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Green",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -22,
                            DateOfBirth = new DateTime(1953, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Johnny",
                            HireDate = new DateTime(2001, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Clark",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -23,
                            DateOfBirth = new DateTime(1969, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Larry",
                            HireDate = new DateTime(2006, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Carter",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -24,
                            DateOfBirth = new DateTime(1979, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Evelyn",
                            HireDate = new DateTime(2007, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ortiz",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -25,
                            DateOfBirth = new DateTime(1977, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            HireDate = new DateTime(2011, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Long",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -26,
                            DateOfBirth = new DateTime(1954, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marilyn",
                            HireDate = new DateTime(2008, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanchez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -27,
                            DateOfBirth = new DateTime(1965, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jean",
                            HireDate = new DateTime(2012, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Adams",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -28,
                            DateOfBirth = new DateTime(1954, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Olivia",
                            HireDate = new DateTime(2003, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Garcia",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -29,
                            DateOfBirth = new DateTime(1954, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Patricia",
                            HireDate = new DateTime(2008, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanders",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -30,
                            DateOfBirth = new DateTime(1977, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "George",
                            HireDate = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gutierrez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -31,
                            DateOfBirth = new DateTime(1975, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Randy",
                            HireDate = new DateTime(2013, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lewis",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -32,
                            DateOfBirth = new DateTime(1978, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Danielle",
                            HireDate = new DateTime(2013, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ross",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -33,
                            DateOfBirth = new DateTime(1969, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeremy",
                            HireDate = new DateTime(2002, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Davis",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -34,
                            DateOfBirth = new DateTime(1961, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Heather",
                            HireDate = new DateTime(2003, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moore",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -35,
                            DateOfBirth = new DateTime(1956, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ralph",
                            HireDate = new DateTime(2002, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -36,
                            DateOfBirth = new DateTime(1973, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Roger",
                            HireDate = new DateTime(2005, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rivera",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -37,
                            DateOfBirth = new DateTime(1974, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marie",
                            HireDate = new DateTime(2014, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Carter",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -38,
                            DateOfBirth = new DateTime(1959, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Evelyn",
                            HireDate = new DateTime(2007, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moore",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -39,
                            DateOfBirth = new DateTime(1959, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Edward",
                            HireDate = new DateTime(2012, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kim",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -40,
                            DateOfBirth = new DateTime(1975, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            HireDate = new DateTime(2003, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gonzales",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -41,
                            DateOfBirth = new DateTime(1957, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gary",
                            HireDate = new DateTime(2011, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Myers",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -42,
                            DateOfBirth = new DateTime(1954, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jesse",
                            HireDate = new DateTime(2010, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hall",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -43,
                            DateOfBirth = new DateTime(1971, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Timothy",
                            HireDate = new DateTime(2008, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "White",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -44,
                            DateOfBirth = new DateTime(1953, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jennifer",
                            HireDate = new DateTime(2006, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Clark",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -45,
                            DateOfBirth = new DateTime(1974, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Barbara",
                            HireDate = new DateTime(2000, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rivera",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -46,
                            DateOfBirth = new DateTime(1959, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Richard",
                            HireDate = new DateTime(2013, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morales",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -47,
                            DateOfBirth = new DateTime(1971, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeffrey",
                            HireDate = new DateTime(2001, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Campbell",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -48,
                            DateOfBirth = new DateTime(1980, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexis",
                            HireDate = new DateTime(2010, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Garcia",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -49,
                            DateOfBirth = new DateTime(1980, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bruce",
                            HireDate = new DateTime(2013, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Turner",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -50,
                            DateOfBirth = new DateTime(1972, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Larry",
                            HireDate = new DateTime(2000, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ward",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -51,
                            DateOfBirth = new DateTime(1951, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Samantha",
                            HireDate = new DateTime(2014, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -52,
                            DateOfBirth = new DateTime(1950, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Vincent",
                            HireDate = new DateTime(2009, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brooks",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -53,
                            DateOfBirth = new DateTime(1956, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Evelyn",
                            HireDate = new DateTime(2002, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reed",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -54,
                            DateOfBirth = new DateTime(1951, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lisa",
                            HireDate = new DateTime(2013, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gonzales",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -55,
                            DateOfBirth = new DateTime(1955, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Victoria",
                            HireDate = new DateTime(2012, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Alvarez",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -56,
                            DateOfBirth = new DateTime(1964, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Helen",
                            HireDate = new DateTime(2005, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Harris",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -57,
                            DateOfBirth = new DateTime(1971, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Benjamin",
                            HireDate = new DateTime(2010, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hall",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -58,
                            DateOfBirth = new DateTime(1951, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            HireDate = new DateTime(2006, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moore",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -59,
                            DateOfBirth = new DateTime(1957, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ann",
                            HireDate = new DateTime(2004, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hill",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -60,
                            DateOfBirth = new DateTime(1960, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeremy",
                            HireDate = new DateTime(2014, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -61,
                            DateOfBirth = new DateTime(1957, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Benjamin",
                            HireDate = new DateTime(2002, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martinez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -62,
                            DateOfBirth = new DateTime(1953, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anthony",
                            HireDate = new DateTime(2011, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "James",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -63,
                            DateOfBirth = new DateTime(1962, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andrew",
                            HireDate = new DateTime(2003, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -64,
                            DateOfBirth = new DateTime(1957, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Janice",
                            HireDate = new DateTime(2009, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jones",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -65,
                            DateOfBirth = new DateTime(1961, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jack",
                            HireDate = new DateTime(2007, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Clark",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -66,
                            DateOfBirth = new DateTime(1964, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dennis",
                            HireDate = new DateTime(2000, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -67,
                            DateOfBirth = new DateTime(1975, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Debra",
                            HireDate = new DateTime(2003, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "White",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -68,
                            DateOfBirth = new DateTime(1975, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Judith",
                            HireDate = new DateTime(2001, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Long",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -69,
                            DateOfBirth = new DateTime(1977, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Betty",
                            HireDate = new DateTime(2000, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -70,
                            DateOfBirth = new DateTime(1959, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mark",
                            HireDate = new DateTime(2005, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cook",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -71,
                            DateOfBirth = new DateTime(1950, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ethan",
                            HireDate = new DateTime(2002, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lee",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -72,
                            DateOfBirth = new DateTime(1974, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Patricia",
                            HireDate = new DateTime(2000, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanchez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -73,
                            DateOfBirth = new DateTime(1955, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Johnny",
                            HireDate = new DateTime(2012, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Howard",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -74,
                            DateOfBirth = new DateTime(1977, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Walter",
                            HireDate = new DateTime(2011, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cook",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -75,
                            DateOfBirth = new DateTime(1973, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Grace",
                            HireDate = new DateTime(2000, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martinez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -76,
                            DateOfBirth = new DateTime(1978, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ryan",
                            HireDate = new DateTime(2008, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jackson",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -77,
                            DateOfBirth = new DateTime(1951, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kyle",
                            HireDate = new DateTime(2012, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Stewart",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -78,
                            DateOfBirth = new DateTime(1963, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Roger",
                            HireDate = new DateTime(2005, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Robinson",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -79,
                            DateOfBirth = new DateTime(1950, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gregory",
                            HireDate = new DateTime(2001, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Torres",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -80,
                            DateOfBirth = new DateTime(1950, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diane",
                            HireDate = new DateTime(2004, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -81,
                            DateOfBirth = new DateTime(1955, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Shirley",
                            HireDate = new DateTime(2012, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Clark",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -82,
                            DateOfBirth = new DateTime(1973, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ashley",
                            HireDate = new DateTime(2014, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morales",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -83,
                            DateOfBirth = new DateTime(1960, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Edward",
                            HireDate = new DateTime(2002, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rivera",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -84,
                            DateOfBirth = new DateTime(1955, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gerald",
                            HireDate = new DateTime(2014, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "White",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -85,
                            DateOfBirth = new DateTime(1954, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexis",
                            HireDate = new DateTime(2002, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Adams",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -86,
                            DateOfBirth = new DateTime(1956, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joan",
                            HireDate = new DateTime(2006, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wood",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -87,
                            DateOfBirth = new DateTime(1960, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Evelyn",
                            HireDate = new DateTime(2002, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morgan",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -88,
                            DateOfBirth = new DateTime(1978, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Karen",
                            HireDate = new DateTime(2013, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rodriguez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -89,
                            DateOfBirth = new DateTime(1979, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christian",
                            HireDate = new DateTime(2005, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Torres",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -90,
                            DateOfBirth = new DateTime(1959, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Donna",
                            HireDate = new DateTime(2006, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wood",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -91,
                            DateOfBirth = new DateTime(1972, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eric",
                            HireDate = new DateTime(2009, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -92,
                            DateOfBirth = new DateTime(1952, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thomas",
                            HireDate = new DateTime(2001, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Harris",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -93,
                            DateOfBirth = new DateTime(1975, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jose",
                            HireDate = new DateTime(2014, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lopez",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -94,
                            DateOfBirth = new DateTime(1967, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amber",
                            HireDate = new DateTime(2014, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Alvarez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -95,
                            DateOfBirth = new DateTime(1960, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amy",
                            HireDate = new DateTime(2001, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roberts",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -96,
                            DateOfBirth = new DateTime(1951, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bruce",
                            HireDate = new DateTime(2009, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ramos",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -97,
                            DateOfBirth = new DateTime(1953, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nancy",
                            HireDate = new DateTime(2012, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gonzales",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -98,
                            DateOfBirth = new DateTime(1971, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Madison",
                            HireDate = new DateTime(2000, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -99,
                            DateOfBirth = new DateTime(1980, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Noah",
                            HireDate = new DateTime(2007, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anderson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -100,
                            DateOfBirth = new DateTime(1966, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sandra",
                            HireDate = new DateTime(2006, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Murphy",
                            LocationID = -4
                        });
                });

            modelBuilder.Entity("_4._1Employee.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnName("postalcode")
                        .HasColumnType("char(6)")
                        .HasMaxLength(6)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("location");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Address = "123 Main Street",
                            City = "Edmonton",
                            Name = "Super Duper Store",
                            PostalCode = "T6M5W2"
                        },
                        new
                        {
                            ID = -2,
                            Address = "567 Side Street",
                            City = "Vancouver",
                            Name = "Awesome Store",
                            PostalCode = "T8M2X2"
                        },
                        new
                        {
                            ID = -3,
                            Address = "246 Boulevard Street",
                            City = "Edmonton",
                            Name = "Corporate Headquarters",
                            PostalCode = "T2Y8Z2"
                        },
                        new
                        {
                            ID = -4,
                            Address = "357 Back Street",
                            City = "Calgary",
                            Name = "Silly Store",
                            PostalCode = "T9T7L2"
                        },
                        new
                        {
                            ID = -5,
                            Address = "852 Sesame Street",
                            City = "Edmonton",
                            Name = "Elmo Store",
                            PostalCode = "T9M2A9"
                        });
                });

            modelBuilder.Entity("_4._1Employee.Employee", b =>
                {
                    b.HasOne("_4._1Employee.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationID")
                        .HasConstraintName("FK_Employee_Location")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
